document.writeln("<!--延迟加载-->");
document.writeln("<!--如果要写自定义内容建议都加到这个延迟加载的范围内-->");
document.writeln("<div id=\"customize\" style=\"display: none;\">");
document.writeln("  <div>");
document.writeln("    <center class=\"dibu\">");
document.writeln("      <div style=\"font-size: 16px;\">");
document.writeln("        <span class=\"nav-item\">");
document.writeln("          <a class=\"nav-link\" href=\"mailto:2422669375@qq.com\" target=\"_blank\">");
document.writeln("            <i class=\"fa-duotone fa-envelope-open\" style=\"color:#409EFF\" aria-hidden=\"true\">");
document.writeln("            </i>");
document.writeln("            邮箱 |");
document.writeln("          </a>");
document.writeln("        </span>");
document.writeln("        <span class=\"nav-item\">");
document.writeln("          <a class=\"nav-link\" href=\"https://github.com/liulep\" target=\"_blank\">");
document.writeln("            <i class=\"fas fa-edit\" style=\"color:#409EFF\" aria-hidden=\"true\">");
document.writeln("            </i>");
document.writeln("            github |");
document.writeln("          </a>");
document.writeln("        </span>");
document.writeln("        <span class=\"nav-item\">");
document.writeln("          <a class=\"nav-link\" href=\"http://pan.liulep.com\" target=\"_blank\">");
document.writeln("            <i class=\"fa fa-cloud-download\" style=\"color:#409EFF;\" aria-hidden=\"true\">");
document.writeln("            </i>");
document.writeln("            云盘 |");
document.writeln("          </a>");
document.writeln("        </span>");
document.writeln("        <!--后台入口-->");
document.writeln("        <span class=\"nav-item\">");
document.writeln("          <a class=\"nav-link\" href=\"/@manage\" target=\"_blank\">");
document.writeln("            <i class=\"fa-solid fa-folder-gear\" style=\"color:#409EFF;\" aria-hidden=\"true\">");
document.writeln("            </i>");
document.writeln("            管理 |");
document.writeln("          </a>");
document.writeln("        </span>");
document.writeln("        <!--版权，请尊重作者-->");
document.writeln("        <span class=\"nav-item\">");
document.writeln("          <a class=\"nav-link\" href=\"https://github.com/Xhofe/alist\" target=\"_blank\">");
document.writeln("            <i class=\"fa-solid fa-copyright\" style=\"color:#409EFF;\" aria-hidden=\"true\">");
document.writeln("            </i>");
document.writeln("            Alist");
document.writeln("          </a>");
document.writeln("        </span>");
document.writeln("      </div>");
document.writeln("      <br />");
document.writeln("      <!--添加备案信息-->");
document.writeln("      <span class=\"nav-item\">");
document.writeln("        <a class=\"nav-link\" href=\"https://beian.miit.gov.cn/#/Integrated/index\" target=\"_blank\">");
document.writeln("          <i class=\"fa-solid fa-shield-check\" style=\"color:#409EFF;\" aria-hidden=\"true\">");
document.writeln("          </i>");
document.writeln("          ©2023 liulep · 湘ICP备2022008118号");
document.writeln("        </a>");
document.writeln("      </span>");
document.writeln("    </center>");
document.writeln("    <br />");
document.writeln("    <br />");
document.writeln("  </div>");
document.writeln("  <!--延迟加载范围到这里结束-->");
document.writeln("</div>");
document.writeln("<!--延迟加载配套使用JS-->");
document.writeln("<script>");
document.writeln("  let interval = setInterval(() => {");
document.writeln("    if (document.querySelector(\".footer\")) {");
document.writeln("      document.querySelector(\"#customize\").style.display = \"\";");
document.writeln("      clearInterval(interval);");
document.writeln("    }");
document.writeln("  }, 200);");
document.writeln("</script>");