document.writeln(" <!--延迟加载-->");
document.writeln(" <div id=\"customize\" style=\"display: none;\">");
document.writeln("   <div>");
document.writeln("     <br />");
document.writeln("     <br />");
document.writeln("     <div class=\"box\">");
document.writeln("       <div class=\"divstyle\">");
document.writeln("         <span class=\"nav-item\">");
document.writeln("           <a id=\"github\" class=\"nav-link item\" href=\"https://github.com/liulep\" target=\"_blank\">");
document.writeln("             GitHub");
document.writeln("           </a>");
document.writeln("         </span>");
document.writeln("       </div>");
document.writeln("       |");
document.writeln("       <div class=\"divstyle\">");
document.writeln("         <span class=\"nav-item\">");
document.writeln("           <a id=\"email\" class=\"nav-link item\" href=\"mailto:2422669375@qq.com\" target=\"_blank\">");
document.writeln("             邮箱");
document.writeln("           </a>");
document.writeln("         </span>");
document.writeln("       </div>");
document.writeln("       |");
document.writeln("       <div class=\"divstyle\">");
document.writeln("         <span class=\"nav-item\">");
document.writeln("           <a id=\"yunpan\" class=\"nav-link item\" href=\"http://pan.liulep.com\" target=\"_self\">");
document.writeln("             云盘");
document.writeln("           </a>");
document.writeln("         </span>");
document.writeln("       </div>");
document.writeln("       |");
document.writeln("       <div class=\"divstyle\">");
document.writeln("         <!--后台入口-->");
document.writeln("         <span class=\"nav-item\">");
document.writeln("           <a id=\"change\" class=\"nav-link item\" href=\"/@manage\" target=\"_self\">");
document.writeln("             管理");
document.writeln("           </a>");
document.writeln("         </span>");
document.writeln("       </div>");
document.writeln("       |");
document.writeln("       <div class=\"divstyle\">");
document.writeln("         <!--版权，请尊重作者-->");
document.writeln("         <span class=\"nav-item\">");
document.writeln("           <a id=\"alist\" class=\"nav-link item\" href=\"https://github.com/Xhofe/alist\" target=\"_blank\">");
document.writeln("             Alist");
document.writeln("           </a>");
document.writeln("         </span>");
document.writeln("       </div>");
document.writeln("       <br />");
document.writeln("       <br />");
document.writeln("       <div>");
document.writeln("         <!--添加备案信息-->");
document.writeln("         <span class=\"nav-item\">");
document.writeln("           <a class=\"nav-link\" href=\"https://beian.miit.gov.cn/#/Integrated/index\" target=\"_blank\">");
document.writeln("             ©2023 liulep · 湘ICP备2022008118号");
document.writeln("           </a>");
document.writeln("         </span>");
document.writeln("       </div>");
document.writeln("       <br />");
document.writeln("       <br />");
document.writeln("     </div>");
document.writeln("   </div>");
document.writeln("   <!--延迟加载配套使用JS-->");
document.writeln("   <script>");
document.writeln("     let interval = setInterval(() => {");
document.writeln("       if ($(\"[class=\'footer hope-stack hope-c-dhzjXW hope-c-PJLV hope-c-PJLV-ihQbspH-css\']\").length > 0) {");
document.writeln("         $(\"#customize\").attr(\"style\", \"\")");
document.writeln("         if (localStorage.getItem(\'token\') == \'\' || localStorage.getItem(\'token\') == undefined) {");
document.writeln("           $(\"#change\").html(\"登录\");");
document.writeln("           $(\"#change\").attr(\"href\", \"/@login\");");
document.writeln("         } else {");
document.writeln("           $(\"#change\").html(\"管理\");");
document.writeln("           $(\"#change\").attr(\"href\", \"/@manage\");");
document.writeln("         }");
document.writeln("         clearInterval(interval);");
document.writeln("       }");
document.writeln("     }, 200);");
document.writeln("     ");
document.writeln("     ");
document.writeln("     $(\"#change\").click(function() {");
document.writeln("       var url = window.location.pathname;");
document.writeln("       if (str.indexOf(\"@manage\") !== -1) {");
document.writeln("         $(\"#customize\").attr(\"style\", \"display:none\")");
document.writeln("       }");
document.writeln("     })");
document.writeln("   </script>");
