document.write(" <!--延迟加载-->");
document.write(" <div id=\"customize\" style=\"display: none;\">");
document.write("   <div>");
document.write("     <br \/>");
document.write("     <br \/>");
document.write("     <div class=\"box\">");
document.write("       <div class=\"divstyle\">");
document.write("         <span class=\"nav-item\">");
document.write("           <a id=\"github\" class=\"nav-link item\" href=\"https:\/\/github.com\/liulep\" target=\"_blank\">");
document.write("             GitHub");
document.write("           <\/a>");
document.write("         <\/span>");
document.write("       <\/div>");
document.write("       |");
document.write("       <div class=\"divstyle\">");
document.write("         <span class=\"nav-item\">");
document.write("           <a id=\"email\" class=\"nav-link item\" href=\"mailto:2422669375@qq.com\" target=\"_blank\">");
document.write("             邮箱");
document.write("           <\/a>");
document.write("         <\/span>");
document.write("       <\/div>");
document.write("       |");
document.write("       <div class=\"divstyle\">");
document.write("         <span class=\"nav-item\">");
document.write("           <a id=\"yunpan\" class=\"nav-link item\" href=\"http:\/\/pan.liulep.com\" target=\"_self\">");
document.write("             云盘");
document.write("           <\/a>");
document.write("         <\/span>");
document.write("       <\/div>");
document.write("       |");
document.write("       <div class=\"divstyle\">");
document.write("         <!--后台入口-->");
document.write("         <span class=\"nav-item\">");
document.write("           <a id=\"change\" class=\"nav-link item\" href=\"\/@manage\" target=\"_self\">");
document.write("             管理");
document.write("           <\/a>");
document.write("         <\/span>");
document.write("       <\/div>");
document.write("       |");
document.write("       <div class=\"divstyle\">");
document.write("         <!--版权，请尊重作者-->");
document.write("         <span class=\"nav-item\">");
document.write("           <a id=\"alist\" class=\"nav-link item\" href=\"https:\/\/github.com\/Xhofe\/alist\" target=\"_blank\">");
document.write("             Alist");
document.write("           <\/a>");
document.write("         <\/span>");
document.write("       <\/div>");
document.write("       <br \/>");
document.write("       <br \/>");
document.write("       <div>");
document.write("         <!--添加备案信息-->");
document.write("         <span class=\"nav-item\">");
document.write("           <a class=\"nav-link\" href=\"https:\/\/beian.miit.gov.cn\/#\/Integrated\/index\" target=\"_blank\">");
document.write("             ©2023 liulep · 湘ICP备2022008118号");
document.write("           <\/a>");
document.write("         <\/span>");
document.write("       <\/div>");
document.write("       <br \/>");
document.write("       <br \/>");
document.write("     <\/div>");
document.write("   <\/div>");
document.write("   <!--延迟加载配套使用JS-->");
document.write("   <script>");
document.write("     let interval = setInterval(() => {");
document.write("       if ($(\"[class='footer hope-stack hope-c-dhzjXW hope-c-PJLV hope-c-PJLV-ihQbspH-css']\").length > 0) {");
document.write("         $(\"#customize\").attr(\"style\", \"\")");
document.write("         if (localStorage.getItem('token') == '' || localStorage.getItem('token') == undefined) {");
document.write("           $(\"#change\").html(\"登录\");");
document.write("           $(\"#change\").attr(\"href\", \"\/@login\");");
document.write("         } else {");
document.write("           $(\"#change\").html(\"管理\");");
document.write("           $(\"#change\").attr(\"href\", \"\/@manage\");");
document.write("         }");
document.write("         clearInterval(interval);");
document.write("       }");
document.write("     }, 200);");
document.write("     \/\/ $(\"#customize\").attr(\"style\", \"\")");
document.write("     $(\"#change\").click(function() {");
document.write("       var url = window.location.pathname;");
document.write("       if (str.indexOf(\"@manage\") !== -1) {");
document.write("         $(\"#customize\").attr(\"style\", \"display:none\")");
document.write("       }");
document.write("     })");
document.write("   <\/script>");
