document.writeln("<!--不蒜子计数器-->");
document.writeln("<script async src=\'//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js\'></script>");
document.writeln("<!--Alist V3建议添加的，已经默认添加了，如果你的没有建议加上-->");
document.writeln("<script src=\'https://polyfill.io/v3/polyfill.min.js?features=String.prototype.replaceAll\'></script>");
document.writeln("");
document.writeln("<style>");
document.writeln("/*底部CSS，.APP .tanle这三个一起的*/");
document.writeln("dibu {");
document.writeln("    border-top: 0px;");
document.writeln("    position: absolute;");
document.writeln("    bottom: 0;");
document.writeln("    width: 100%;");
document.writeln("    margin: 0px;");
document.writeln("    padding: 0px;");
document.writeln("}");
document.writeln(".App {");
document.writeln("    min-height: 85vh;");
document.writeln("}");
document.writeln(".table {");
document.writeln("    margin: auto;");
document.writeln("}");
document.writeln("/*去掉底部*/");
document.writeln(".footer {");
document.writeln("    display: none !important;");
document.writeln("}");
document.writeln("");
document.writeln("</style>");
document.writeln("");
