document.writeln("<!--不蒜子计数器-->");
document.writeln("<script async src=\'//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js\'></script>");
document.writeln("<!--Alist V3建议添加的，已经默认添加了，如果你的没有建议加上-->");
document.writeln("<script src=\'https://polyfill.io/v3/polyfill.min.js?features=String.prototype.replaceAll\'></script>");
document.writeln("<!--引入字体，全局字体使用-->");
document.writeln("<link rel=\'stylesheet\' href=\'https://npm.elemecdn.com/lxgw-wenkai-webfont@1.1.0/lxgwwenkai-regular.css\' />");
document.writeln("<!-- Font6，自定义底部使用和看板娘使用的图标和字体文件-->");
document.writeln("<link type=\'text/css\' rel=\'stylesheet\' href=\'https://npm.elemecdn.com/font6pro@6.0.1/css/fontawesome.min.css\' media=\'all\'>");
document.writeln("<link href=\'https://npm.elemecdn.com/font6pro@6.0.1/css/all.min.css\' rel=\'stylesheet\'>");
document.writeln("");
document.writeln("<style>");
document.writeln("/*底部CSS，.APP .tanle这三个一起的*/");
document.writeln("dibu {");
document.writeln("    border-top: 0px;");
document.writeln("    position: absolute;");
document.writeln("    bottom: 0;");
document.writeln("    width: 100%;");
document.writeln("    margin: 0px;");
document.writeln("    padding: 0px;");
document.writeln("}");
document.writeln(".App {");
document.writeln("    min-height: 85vh;");
document.writeln("}");
document.writeln(".table {");
document.writeln("    margin: auto;");
document.writeln("}");
document.writeln("/*去掉底部*/");
document.writeln(".footer {");
document.writeln("    display: none !important;");
document.writeln("}");
document.writeln("");
document.writeln("</style>");
document.writeln("");