document.write("    <!--Alist V3默认添加-->");
document.write("    <script src=\"https:\/\/polyfill.io\/v3\/polyfill.min.js?features=String.prototype.replaceAll\"><\/script>");
document.write("    <!--jQuery-->");
document.write("    <script src=\"https:\/\/ajax.aspnetcdn.com\/ajax\/jquery\/jquery-1.9.0.min.js\"><\/script>");
document.write("    <style>");
document.write("      \/*去掉底部*\/");
document.write("      .footer {");
document.write("        display: none !important;");
document.write("      }");
document.write("");
document.write("      .box {");
document.write("        text-align: center;");
document.write("        width: 100%;");
document.write("        height: 50px;");
document.write("      }");
document.write("");
document.write("      .item {");
document.write("        padding: 5px 10px;");
document.write("        font-size: 16px;");
document.write("        position: relative;");
document.write("        cursor: pointer;");
document.write("        transition: all 0.3s;");
document.write("      }");
document.write("");
document.write("      .item:after {");
document.write("        display: block;");
document.write("        content: '';");
document.write("        width: 0;");
document.write("        height: 4px;");
document.write("        position: absolute;");
document.write("        bottom: 0;");
document.write("        left: 50%;");
document.write("        transform: translateX(-50%);");
document.write("        background-color: rgb(24, 144, 255);");
document.write("        transition: all 0.3s;");
document.write("      }");
document.write("      .divstyle {");
document.write("        display: inline-block;");
document.write("        border:4px solid transparent;");
document.write("        transition: all 0.1s;");
document.write("      }");
document.write("      .divstyle:hover {");
document.write("        display: inline-block;");
document.write("        bottom: none;");
document.write("        transition: all 0.3s;");
document.write("      }");
document.write("      .item:hover:after {");
document.write("        display: block;");
document.write("        content: '';");
document.write("        width: 80%;");
document.write("        height: 4px;");
document.write("        background-color: rgb(24, 144, 255);");
document.write("        transition: all 0.3s;");
document.write("      }");
document.write("      .item:hover {");
document.write("        font-size: 20px;");
document.write("        transition: all 0.3s;");
document.write("      }");
document.write("    <\/style>");
